name: test-environment
channels:
  - conda-forge
dependencies:
  - xarray!=2022.9.0
  - dask
  - distributed
  - dask-image
  - donfig
  - appdirs
  - toolz
  - Cython
  - numba
  - sphinx
  - cartopy
  - panel>=0.12.7
  - pillow
  - matplotlib
  - scipy
  - pyyaml
  - pyproj
  - pyresample>=1.24
  - coveralls
  - coverage
  - codecov
  - behave
  - netcdf4
  - h5py
  - h5netcdf
  - gdal
  - rasterio
  - bottleneck
  - rioxarray
  - defusedxml
  - imageio
  - pyhdf
  - mock
  - libtiff
  - geoviews
  - holoviews
  - hvplot
  - zarr
  - python-eccodes
  # 2.19.1 seems to cause library linking issues
  - eccodes>=2.20
  - pytest
  - pytest-cov
  - pytest-lazy-fixture
  - fsspec
  - s3fs
  - python-geotiepoints
  - pooch
  - pip
  - skyfield
  - astropy
  - xarray-datatree
  - pint-xarray
  - ephem
  - bokeh
  - pip:
    - trollsift
    - trollimage>=1.20
    - pyspectral
    - pyorbital
